import type { Ride, Accommodation, Booking } from "@shared/schema";

export const mockRides: Ride[] = [
  {
    id: "ride-1",
    type: "UberX",
    fromAddress: "Downtown",
    toAddress: "Airport",
    fromLat: "40.7128",
    fromLng: "-74.0060",
    toLat: "40.6892",
    toLng: "-74.1745",
    price: "12.50",
    estimatedDuration: 15,
    estimatedDistance: "8.2",
    availableIn: 4,
    driverName: "John Doe",
    vehicleInfo: "Honda Civic - ABC 123",
    isActive: true,
  },
  {
    id: "ride-2",
    type: "Comfort",
    fromAddress: "Downtown",
    toAddress: "Airport",
    fromLat: "40.7128",
    fromLng: "-74.0060",
    toLat: "40.6892",
    toLng: "-74.1745",
    price: "18.25",
    estimatedDuration: 15,
    estimatedDistance: "8.2",
    availableIn: 6,
    driverName: "Jane Smith",
    vehicleInfo: "Toyota Camry - XYZ 789",
    isActive: true,
  },
  {
    id: "ride-3",
    type: "UberXL",
    fromAddress: "Downtown",
    toAddress: "Airport",
    fromLat: "40.7128",
    fromLng: "-74.0060",
    toLat: "40.6892",
    toLng: "-74.1745",
    price: "22.75",
    estimatedDuration: 15,
    estimatedDistance: "8.2",
    availableIn: 8,
    driverName: "Mike Johnson",
    vehicleInfo: "Honda Pilot - DEF 456",
    isActive: true,
  },
];

export const mockAccommodations: Accommodation[] = [
  {
    id: "acc-1",
    name: "Grand Plaza Hotel",
    type: "Hotel",
    address: "Downtown • 2.1 km from center",
    lat: "40.7589",
    lng: "-73.9851",
    pricePerNight: "185.00",
    rating: "4.8",
    reviewCount: 342,
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945"],
    amenities: ["WiFi", "Pool", "Gym", "Restaurant"],
    description: "Luxury hotel in downtown with city views",
    distanceFromCenter: "2.1",
    isAvailable: true,
  },
  {
    id: "acc-2",
    name: "Boutique Suites",
    type: "Hotel",
    address: "Arts District • 1.8 km from center",
    lat: "40.7505",
    lng: "-73.9934",
    pricePerNight: "145.00",
    rating: "4.6",
    reviewCount: 198,
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4"],
    amenities: ["WiFi", "Breakfast", "Parking"],
    description: "Stylish boutique hotel in arts district",
    distanceFromCenter: "1.8",
    isAvailable: true,
  },
  {
    id: "acc-3",
    name: "Executive Inn",
    type: "Hotel",
    address: "Business District • 3.2 km from center",
    lat: "40.7614",
    lng: "-73.9776",
    pricePerNight: "125.00",
    rating: "4.7",
    reviewCount: 256,
    images: ["https://images.unsplash.com/photo-1578683010236-d716f9a3f461"],
    amenities: ["WiFi", "Business Center", "Gym"],
    description: "Modern business hotel with workspace",
    distanceFromCenter: "3.2",
    isAvailable: true,
  },
  {
    id: "acc-4",
    name: "Modern Loft",
    type: "Apartment",
    address: "Trendy Neighborhood • 2.5 km from center",
    lat: "40.7282",
    lng: "-73.9942",
    pricePerNight: "95.00",
    rating: "4.5",
    reviewCount: 89,
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267"],
    amenities: ["WiFi", "Kitchen", "Washing Machine"],
    description: "Stylish modern apartment rental",
    distanceFromCenter: "2.5",
    isAvailable: true,
  },
];

export const mockBookings: Booking[] = [
  {
    id: "booking-1",
    userId: "user-1",
    type: "ride",
    status: "completed",
    rideId: "ride-1",
    totalPrice: "12.50",
    paymentMethod: "visa_4242",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    pickupTime: new Date("2024-01-15T10:30:00"),
    accommodationId: null,
    checkInDate: null,
    checkOutDate: null,
    guests: null,
    nights: null,
  },
  {
    id: "booking-2",
    userId: "user-1",
    type: "stay",
    status: "completed",
    accommodationId: "acc-3",
    totalPrice: "250.00",
    paymentMethod: "visa_4242",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    checkInDate: new Date("2024-01-12"),
    checkOutDate: new Date("2024-01-14"),
    guests: 1,
    nights: 2,
    rideId: null,
    pickupTime: null,
  },
];
